// <auto-generated />
namespace GameRecordApplication.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class IsTeamGame_Column_Games : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(IsTeamGame_Column_Games));
        
        string IMigrationMetadata.Id
        {
            get { return "201911070240509_IsTeamGame_Column_Games"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
