// <auto-generated />
namespace GameRecordApplication.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Required_DotaHeroAttr : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Required_DotaHeroAttr));
        
        string IMigrationMetadata.Id
        {
            get { return "201911200003302_Required_DotaHeroAttr"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
